// THIS FILE IS AUTOMATICALLY GENERATED. DO NOT MODIFY IT.

import { Asset, Entry } from "contentful"
import { Document } from "@contentful/rich-text-types"

interface ICardListFields {
  /** Headline */
  headline: string | null

  /** Card Color */
  cardColor: "Blue" | "Coral" | "Tan" | "Teal" | "Yellow" | "Violet"

  /** Footnote */
  footnote: string | null

  /** Cards */
  cards: (ICrosslinkCard)[]
}

export interface ICardList extends Entry<ICardListFields> {}

interface ICheckmarksFields {
  /** Checkmark Text */
  checkmarkText: (string)[]
}

export interface ICheckmarks extends Entry<ICheckmarksFields> {}

interface IComplianceLogoFields {
  /** Image */
  image: Asset

  /** Title */
  title: string

  /** Description */
  description: string
}

export interface IComplianceLogo extends Entry<IComplianceLogoFields> {}

interface IComplianceLogoPondFields {
  /** Title */
  title: string

  /** Logos */
  logos: (IComplianceLogo)[]
}

export interface IComplianceLogoPond extends Entry<IComplianceLogoPondFields> {}

interface ICrosslinkCardFields {
  /** Title */
  title: string

  /** Body Text */
  bodyText: string

  /** Icon */
  icon: Asset | null

  /** CTA */
  cta: ICtaLink | null

  /** Card Color */
  cardColor: "Blue" | "Coral" | "Tan" | "Teal" | "Yellow" | "Violet"
}

export interface ICrosslinkCard extends Entry<ICrosslinkCardFields> {}

interface ICtaLinkFields {
  /** Label */
  label: string

  /** URL */
  url: string

  /** Color */
  color: "Black" | "White" | "Teal" | "Tan"

  /** Open in New Window */
  openInNewWindow: boolean
}

export interface ICtaLink extends Entry<ICtaLinkFields> {}

interface IEmailCaptureFields {
  /** Heading */
  heading: string

  /** Eyebrow */
  eyebrow: string | null

  /** Full-width */
  fullWidth: boolean | null

  /** Background Color */
  bgColor: "Yellow" | "Teal"

  /** Background Image */
  bgImage: boolean | null

  /** CTA */
  cta: ICtaLink | null

  /** Checkmarks */
  checkmarks: (ICheckmarks)[] | null
}

export interface IEmailCapture extends Entry<IEmailCaptureFields> {}

interface IFeatureAnnouncementFields {
  /** Entry Description */
  description: string | null

  /** Eyebrow */
  eyebrow: string

  /** Title */
  title: string

  /** Icon */
  icon: Asset | null

  /** Image */
  image: Asset

  /** Include NEW Animation */
  newSticker: boolean | null

  /** Image on left? */
  flipped: boolean | null

  /** Background Color */
  bgColor: "Tan" | "Teal"

  /** CTA 1 */
  cta1: ICtaLink

  /** CTA 2 */
  cta2: ICtaLink | null
}

export interface IFeatureAnnouncement extends Entry<IFeatureAnnouncementFields> {}

interface IFeatureSpotlightFields {
  /** Eyebrow */
  eyebrow: string | null

  /** Heading */
  heading: string

  /** Subheading */
  subheading: string | null

  /** Product Image */
  productImage: Asset

  /** Icon */
  icon: Asset | null

  /** Background Color */
  bgColor: "Tan" | "Teal" | "Coral" | "Yellow" | "White"

  /** CTA */
  cta: ICtaLink | null

  /** Image side */
  imageSide: boolean
}

export interface IFeatureSpotlight extends Entry<IFeatureSpotlightFields> {}

interface IFeatureSpotlightCitationFields {
  /** Heading */
  heading: string

  /** Eyebrow */
  eyebrow: string | null

  /** Subheading */
  subheading: string | null

  /** Product Image */
  productImage: Asset

  /** Citation Quote */
  citationQuote: string

  /** Citation Source */
  citationSource: string

  /** Citation Publication Title */
  citationPublicationTitle: string

  /** Citation URL */
  citationUrl: string

  /** Icon */
  icon: Asset | null

  /** Background Color */
  bgColor: "Teal" | "Tan" | "Coral" | "White" | "Yellow"

  /** Image Side */
  imageSide: boolean

  /** CTA */
  cta: ICtaLink | null
}

export interface IFeatureSpotlightCitation extends Entry<IFeatureSpotlightCitationFields> {}

interface IFeatureSpotlightVerticalFields {
  /** Heading */
  heading: string

  /** Eyebrow */
  eyebrow: string | null

  /** Subheading */
  subheading: string | null

  /** CTA */
  cta: ICtaLink | null

  /** Image */
  image: Asset

  /** Arrow on Right? */
  arrowOnRight: boolean | null

  /** Background Color */
  backgroundColor: "Coral" | "Tan" | "Teal" | "Yellow" | "White" | null
}

export interface IFeatureSpotlightVertical extends Entry<IFeatureSpotlightVerticalFields> {}

interface IFooterFields {
  /** Sections */
  sections: (IFooterSection)[]
}

export interface IFooter extends Entry<IFooterFields> {}

interface IFooterSectionFields {
  /** Title */
  title: string

  /** Content */
  content: Document
}

export interface IFooterSection extends Entry<IFooterSectionFields> {}

interface IGatedContentFields {
  /** Heading */
  heading: string

  /** Subheading */
  subheading: string

  /** Background Color */
  bgColor: "Yellow" | "Teal" | "Tan" | "Coral"

  /** Submit Button Text */
  submitButtonText: string
}

export interface IGatedContent extends Entry<IGatedContentFields> {}

interface IHeroEmailCaptureFields {
  /** Eyebrow */
  eyebrow: string | null

  /** Headline */
  headline: string

  /** Subheading */
  subheading: string | null

  /** Left Align */
  leftAlign: boolean

  /** Background Image */
  bgImage: Asset | null

  /** Checkmarks */
  checkmarks: (ICheckmarks)[] | null
}

export interface IHeroEmailCapture extends Entry<IHeroEmailCaptureFields> {}

interface IJumbotronHeaderFields {
  /** Content */
  content: Document
}

export interface IJumbotronHeader extends Entry<IJumbotronHeaderFields> {}

interface ILargeTestimonialFields {
  /** Quote */
  quote: string

  /** Name */
  name: string

  /** Job Title */
  jobTitle: string

  /** Company Name */
  companyName: string

  /** Company Logo */
  companyLogo: Asset

  /** Product Text */
  productText: string | null

  /** Products */
  products:
    | ("Messenger" | "Answer Bot" | "Articles" | "Customer Data Platform" | "Inbox" | "Messages")[]
    | null

  /** Portrait */
  portrait: Asset

  /** Background Color */
  bgColor: "Tan" | "Teal" | "Yellow"

  /** CTA */
  cta: ICtaLink | null
}

export interface ILargeTestimonial extends Entry<ILargeTestimonialFields> {}

interface ILayoutFields {
  /** Name */
  name: string

  /** Navigation */
  navigation: INavigation

  /** Footer */
  footer: IFooter
}

export interface ILayout extends Entry<ILayoutFields> {}

interface ILogoFields {
  /** Company Logo */
  logoUrl: Asset

  /** Company Name */
  companyName: string
}

export interface ILogo extends Entry<ILogoFields> {}

interface ILogoPartyFields {
  /** Heading */
  heading: string

  /** Subheading */
  subheading: string | null

  /** Background Color */
  bgColor: "Coral" | "Tan" | "Teal" | "White" | "Yellow"

  /** Logos */
  logos: (ILogo)[]

  /** CTA */
  cta: ICtaLink | null
}

export interface ILogoParty extends Entry<ILogoPartyFields> {}

interface IMarketoFormFields {
  /** Name */
  name: string | null

  /** Marketo form */
  marketoForm: Record<string, any>
}

export interface IMarketoForm extends Entry<IMarketoFormFields> {}

interface IMiniTestimonialsFields {
  /** Testimonials */
  testimonials: (ITestimonialMiniCard)[]
}

export interface IMiniTestimonials extends Entry<IMiniTestimonialsFields> {}

interface INavigationFields {
  /** Title */
  title: string | null

  /** Top Level Items */
  topLevelItems: (INavigationTopLevelItem)[]

  /** Signup CTA */
  signupCta: ISignupCta | null
}

export interface INavigation extends Entry<INavigationFields> {}

interface INavigationItemFields {
  /** Label */
  label: string

  /** Description */
  description: string | null

  /** URL */
  url: string
}

export interface INavigationItem extends Entry<INavigationItemFields> {}

interface INavigationMenuFields {
  /** Title */
  title: string

  /** Content */
  content: Document
}

export interface INavigationMenu extends Entry<INavigationMenuFields> {}

interface INavigationSectionFields {
  /** Title */
  title: string | null

  /** Items */
  items: (INavigationItem)[]
}

export interface INavigationSection extends Entry<INavigationSectionFields> {}

interface INavigationTopLevelItemFields {
  /** Title */
  title: string

  /** URL */
  url: string | null

  /** Content */
  content: Document | null

  /** Show subnav on left */
  showSubnavOnLeft: boolean | null
}

export interface INavigationTopLevelItem extends Entry<INavigationTopLevelItemFields> {}

interface IPageFields {
  /** Path */
  path: string

  /** Title */
  title: string

  /** SEO Metadata */
  seoMetadata: ISeoMetadata

  /** Layout */
  layout: ILayout | null

  /** Content */
  content: Document | null
}

export interface IPage extends Entry<IPageFields> {}

interface IPriceFields {
  /** Amount */
  amount: number

  /** Product */
  product: string

  /** Currency */
  currency: string
}

export interface IPrice extends Entry<IPriceFields> {}

interface IRooflineBannerFields {
  /** Message */
  message: string

  /** CTA Text */
  ctaText: string

  /** CTA URL */
  ctaUrl: string

  /** Background Color */
  backgroundColor: "Blue" | "Coral" | "Teal" | "Violet" | "Yellow"
}

export interface IRooflineBanner extends Entry<IRooflineBannerFields> {}

interface ISecurityFeatureFields {
  /** Title */
  title: string

  /** Description */
  description: Document
}

export interface ISecurityFeature extends Entry<ISecurityFeatureFields> {}

interface ISecurityFeatureCategoryFields {
  /** Icon */
  icon: Asset

  /** Title */
  title: string

  /** Button label */
  buttonLabel: string

  /** Features */
  features: (ISecurityFeature)[]
}

export interface ISecurityFeatureCategory extends Entry<ISecurityFeatureCategoryFields> {}

interface ISecurityFeaturesSectionFields {
  /** Title */
  title: string

  /** GDPR Button Label */
  gdprButtonLabel: string

  /** Feature categories */
  featureCategories: (ISecurityFeatureCategory)[]
}

export interface ISecurityFeaturesSection extends Entry<ISecurityFeaturesSectionFields> {}

interface ISecurityFooterFields {
  /** Title */
  title: string

  /** Content */
  content: Document
}

export interface ISecurityFooter extends Entry<ISecurityFooterFields> {}

interface ISeoMetadataFields {
  /** Meta Title */
  metaTitle: string

  /** Meta Description */
  metaDescription: string

  /** OpenGraph Title */
  openGraphTitle: string

  /** OpenGraph Description */
  openGraphDescription: string

  /** OpenGraph Image */
  openGraphImage: Asset

  /** Meta Keywords */
  metaKeywords: (string)[]

  /** Disable Crawling */
  disableCrawling: boolean

  /** Canonical Tag */
  metaCanonical: string | null
}

export interface ISeoMetadata extends Entry<ISeoMetadataFields> {}

interface ISignupCtaFields {
  /** Placeholder */
  placeholder: string

  /** Button label */
  buttonLabel: string
}

export interface ISignupCta extends Entry<ISignupCtaFields> {}

interface ITestimonialMiniCardFields {
  /** Quote */
  quote: string

  /** Name */
  name: string

  /** Job Title */
  jobTitle: string

  /** Company Name */
  companyName: string

  /** Company Logo */
  companyLogo: Asset

  /** Portrait */
  portrait: Asset

  /** External Link */
  externalLink: string | null
}

export interface ITestimonialMiniCard extends Entry<ITestimonialMiniCardFields> {}
