import renderContentfulImports from "../../../src/renderers/contentful/renderContentfulImports"
import format from "../../support/format"

describe("renderContentfulImports()", () => {
  it("renders the top of the codegen file", () => {
    expect(format(renderContentfulImports())).toMatchInlineSnapshot(`
      "// THIS FILE IS AUTOMATICALLY GENERATED. DO NOT MODIFY IT.

      import { Asset, Entry } from \\"contentful\\";
      import { Document } from \\"@contentful/rich-text-types\\";"
    `)
  })

  it("renders the localized top of the codegen file", () => {
    expect(format(renderContentfulImports(true))).toMatchInlineSnapshot(`
      "// THIS FILE IS AUTOMATICALLY GENERATED. DO NOT MODIFY IT.

      import { Entry } from \\"contentful\\";
      import { Document } from \\"@contentful/rich-text-types\\";"
    `)
  })
})
