import renderContentfulImports from "../../../src/renderers/contentful/renderContentfulImports"
import format from "../../support/format"

describe("renderContentfulImports()", () => {
  it("renders the top of the codegen file", () => {
    expect(format(renderContentfulImports())).toMatchInlineSnapshot(`
"// THIS FILE IS AUTOMATICALLY GENERATED. DO NOT MODIFY IT.

import { Asset, Entry } from \\"contentful\\";
import { Document } from \\"@contentful/rich-text-types\\";"
`)
  })

  it("renders the localized top of the codegen file", () => {
    expect(format(renderContentfulImports(true))).toMatchInlineSnapshot(`
      "// THIS FILE IS AUTOMATICALLY GENERATED. DO NOT MODIFY IT.

      import { Entry } from \\"contentful\\";
      import { Document } from \\"@contentful/rich-text-types\\";

      // We have to use our own localized version of Asset because of a bug in contentful https://github.com/contentful/contentful.js/issues/208
      interface Asset {
        sys: Sys;
        fields: {
          title: string,
          description: string,
          file: {
            url: string,
            details: {
              size: number,
              image?: {
                width: number,
                height: number
              }
            },
            fileName: string,
            contentType: string
          }
        };
        toPlainObject(): object;
      }"
    `)
  })
})
