import { ContentType } from "contentful"
import renderContentType from "./renderers/contentful/renderContentType"

export async function generateTypes(contentTypes: ContentType[]) {
  let source = ""

  contentTypes
    .sort((a, b) => a.sys.id.localeCompare(b.sys.id))
    .forEach(contentType => {
      source += renderContentType(contentType)
    })

  return source
}

const contentTypes = [
  {
    sys: {
      space: { sys: { type: "Link", linkType: "Space", id: "xny2w179f4ki" } },
      id: "largeTestimonial",
      type: "ContentType",
      createdAt: "2019-02-20T01:04:37.642Z",
      updatedAt: "2019-02-20T19:04:42.807Z",
      environment: { sys: { id: "master", type: "Link", linkType: "Environment" } },
      publishedVersion: 7,
      publishedAt: "2019-02-20T19:04:42.807Z",
      firstPublishedAt: "2019-02-20T01:04:38.034Z",
      createdBy: {
        sys: { type: "Link", linkType: "User", id: "3ydnlNuap950mQsaT0TzKZ" },
      },
      updatedBy: {
        sys: { type: "Link", linkType: "User", id: "3ydnlNuap950mQsaT0TzKZ" },
      },
      publishedCounter: 4,
      version: 8,
      publishedBy: {
        sys: { type: "Link", linkType: "User", id: "3ydnlNuap950mQsaT0TzKZ" },
      },
    },
    displayField: "companyName",
    name: "Large Testimonial",
    description: "A headshot image paired with a quote and company logo. ",
    fields: [
      {
        id: "quote",
        name: "Quote",
        type: "Symbol",
        localized: false,
        required: true,
        validations: [],
        disabled: false,
        omitted: false,
      },
      {
        id: "name",
        name: "Name",
        type: "Symbol",
        localized: false,
        required: true,
        validations: [],
        disabled: false,
        omitted: false,
      },
      {
        id: "jobTitle",
        name: "Job Title",
        type: "Symbol",
        localized: false,
        required: true,
        validations: [],
        disabled: false,
        omitted: false,
      },
      {
        id: "companyName",
        name: "Company Name",
        type: "Symbol",
        localized: false,
        required: true,
        validations: [],
        disabled: false,
        omitted: false,
      },
      {
        id: "companyLogo",
        name: "Company Logo",
        type: "Link",
        localized: false,
        required: true,
        validations: [{ linkMimetypeGroup: ["image"] }],
        disabled: false,
        omitted: false,
        linkType: "Asset",
      },
      {
        id: "productText",
        name: "Product Text",
        type: "Symbol",
        localized: false,
        required: false,
        validations: [],
        disabled: false,
        omitted: false,
      },
      {
        id: "products",
        name: "Products",
        type: "Array",
        localized: false,
        required: false,
        validations: [],
        disabled: false,
        omitted: false,
        items: {
          type: "Symbol",
          validations: [
            {
              in: [
                "Messenger",
                "Answer Bot",
                "Articles",
                "Customer Data Platform",
                "Inbox",
                "Messages",
              ],
            },
          ],
        },
      },
      {
        id: "portrait",
        name: "Portrait",
        type: "Link",
        localized: false,
        required: true,
        validations: [{ linkMimetypeGroup: ["image"] }],
        disabled: false,
        omitted: false,
        linkType: "Asset",
      },
      {
        id: "cta",
        name: "CTA",
        type: "Link",
        localized: false,
        required: false,
        validations: [{ linkContentType: ["optionalCta"] }],
        disabled: false,
        omitted: false,
        linkType: "Entry",
      },
      {
        id: "bgColor",
        name: "Background Color",
        type: "Symbol",
        localized: false,
        required: true,
        validations: [{ in: ["Tan", "Teal", "Yellow"] }],
        disabled: false,
        omitted: false,
      },
    ],
  },
  {
    sys: {
      space: { sys: { type: "Link", linkType: "Space", id: "xny2w179f4ki" } },
      id: "navigationItem",
      type: "ContentType",
      createdAt: "2019-01-10T06:00:40.663Z",
      updatedAt: "2019-01-14T22:48:42.972Z",
      environment: { sys: { id: "master", type: "Link", linkType: "Environment" } },
      publishedVersion: 5,
      publishedAt: "2019-01-14T22:48:42.972Z",
      firstPublishedAt: "2019-01-10T06:00:41.015Z",
      createdBy: {
        sys: { type: "Link", linkType: "User", id: "04Z9KRmPanYsqyiqFoU1om" },
      },
      updatedBy: {
        sys: { type: "Link", linkType: "User", id: "04Z9KRmPanYsqyiqFoU1om" },
      },
      publishedCounter: 3,
      version: 6,
      publishedBy: {
        sys: { type: "Link", linkType: "User", id: "04Z9KRmPanYsqyiqFoU1om" },
      },
    },
    displayField: "label",
    name: "Navigation Item",
    description: "",
    fields: [
      {
        id: "label",
        name: "Label",
        type: "Symbol",
        localized: true,
        required: true,
        validations: [],
        disabled: false,
        omitted: false,
      },
      {
        id: "description",
        name: "Description",
        type: "Text",
        localized: true,
        required: false,
        validations: [],
        disabled: false,
        omitted: false,
      },
      {
        id: "url",
        name: "URL",
        type: "Symbol",
        localized: false,
        required: true,
        validations: [],
        disabled: false,
        omitted: false,
      },
    ],
  },
  {
    sys: {
      space: { sys: { type: "Link", linkType: "Space", id: "xny2w179f4ki" } },
      id: "checkmarks",
      type: "ContentType",
      createdAt: "2019-02-28T18:55:11.796Z",
      updatedAt: "2019-02-28T19:15:58.323Z",
      environment: { sys: { id: "master", type: "Link", linkType: "Environment" } },
      publishedVersion: 3,
      publishedAt: "2019-02-28T19:15:58.323Z",
      firstPublishedAt: "2019-02-28T18:55:12.171Z",
      createdBy: {
        sys: { type: "Link", linkType: "User", id: "3ypfTkhVi28ATJHO2MIpS7" },
      },
      updatedBy: {
        sys: { type: "Link", linkType: "User", id: "3ypfTkhVi28ATJHO2MIpS7" },
      },
      publishedCounter: 2,
      version: 4,
      publishedBy: {
        sys: { type: "Link", linkType: "User", id: "3ypfTkhVi28ATJHO2MIpS7" },
      },
    },
    displayField: null,
    name: "Checkmarks",
    description: "Three checkmark images with accompanying text",
    fields: [
      {
        id: "checkmarkText",
        name: "Checkmark Text",
        type: "Array",
        localized: false,
        required: true,
        validations: [{ size: { min: 3, max: 3 } }],
        disabled: false,
        omitted: false,
        items: { type: "Symbol", validations: [] },
      },
    ],
  },
  {
    sys: {
      space: { sys: { type: "Link", linkType: "Space", id: "xny2w179f4ki" } },
      id: "complianceLogoPond",
      type: "ContentType",
      createdAt: "2018-12-19T22:31:56.985Z",
      updatedAt: "2018-12-20T23:50:36.641Z",
      environment: { sys: { id: "master", type: "Link", linkType: "Environment" } },
      publishedVersion: 9,
      publishedAt: "2018-12-20T23:50:36.641Z",
      firstPublishedAt: "2018-12-19T22:31:57.426Z",
      createdBy: {
        sys: { type: "Link", linkType: "User", id: "04Z9KRmPanYsqyiqFoU1om" },
      },
      updatedBy: {
        sys: { type: "Link", linkType: "User", id: "04Z9KRmPanYsqyiqFoU1om" },
      },
      publishedCounter: 5,
      version: 10,
      publishedBy: {
        sys: { type: "Link", linkType: "User", id: "04Z9KRmPanYsqyiqFoU1om" },
      },
    },
    displayField: "title",
    name: "Compliance Logo Pond",
    description: "",
    fields: [
      {
        id: "title",
        name: "Title",
        type: "Symbol",
        localized: false,
        required: true,
        validations: [],
        disabled: false,
        omitted: false,
      },
      {
        id: "logos",
        name: "Logos",
        type: "Array",
        localized: false,
        required: true,
        validations: [],
        disabled: false,
        omitted: false,
        items: {
          type: "Link",
          validations: [{ linkContentType: ["complianceLogo"] }],
          linkType: "Entry",
        },
      },
    ],
  },
  {
    sys: {
      space: { sys: { type: "Link", linkType: "Space", id: "xny2w179f4ki" } },
      id: "navigationMenu",
      type: "ContentType",
      createdAt: "2019-01-10T06:06:45.838Z",
      updatedAt: "2019-01-10T06:06:46.321Z",
      environment: { sys: { id: "master", type: "Link", linkType: "Environment" } },
      publishedVersion: 1,
      publishedAt: "2019-01-10T06:06:46.321Z",
      firstPublishedAt: "2019-01-10T06:06:46.321Z",
      createdBy: {
        sys: { type: "Link", linkType: "User", id: "04Z9KRmPanYsqyiqFoU1om" },
      },
      updatedBy: {
        sys: { type: "Link", linkType: "User", id: "04Z9KRmPanYsqyiqFoU1om" },
      },
      publishedCounter: 1,
      version: 2,
      publishedBy: {
        sys: { type: "Link", linkType: "User", id: "04Z9KRmPanYsqyiqFoU1om" },
      },
    },
    displayField: "title",
    name: "Navigation Menu",
    description: "",
    fields: [
      {
        id: "title",
        name: "Title",
        type: "Symbol",
        localized: false,
        required: true,
        validations: [],
        disabled: false,
        omitted: false,
      },
      {
        id: "content",
        name: "Content",
        type: "RichText",
        localized: false,
        required: true,
        validations: [{ nodes: {} }],
        disabled: false,
        omitted: false,
      },
    ],
  },
  {
    sys: {
      space: { sys: { type: "Link", linkType: "Space", id: "xny2w179f4ki" } },
      id: "navigationTopLevelItem",
      type: "ContentType",
      createdAt: "2019-01-10T06:08:30.584Z",
      updatedAt: "2019-01-15T00:14:41.635Z",
      environment: { sys: { id: "master", type: "Link", linkType: "Environment" } },
      publishedVersion: 19,
      publishedAt: "2019-01-15T00:14:41.634Z",
      firstPublishedAt: "2019-01-10T06:08:31.101Z",
      createdBy: {
        sys: { type: "Link", linkType: "User", id: "04Z9KRmPanYsqyiqFoU1om" },
      },
      updatedBy: {
        sys: { type: "Link", linkType: "User", id: "04Z9KRmPanYsqyiqFoU1om" },
      },
      publishedCounter: 10,
      version: 20,
      publishedBy: {
        sys: { type: "Link", linkType: "User", id: "04Z9KRmPanYsqyiqFoU1om" },
      },
    },
    displayField: "title",
    name: "Navigation Top Level Item",
    description: "",
    fields: [
      {
        id: "title",
        name: "Title",
        type: "Symbol",
        localized: true,
        required: true,
        validations: [],
        disabled: false,
        omitted: false,
      },
      {
        id: "url",
        name: "URL",
        type: "Symbol",
        localized: false,
        required: false,
        validations: [],
        disabled: false,
        omitted: false,
      },
      {
        id: "content",
        name: "Content",
        type: "RichText",
        localized: false,
        required: false,
        validations: [{ nodes: {} }],
        disabled: false,
        omitted: false,
      },
      {
        id: "showSubnavOnLeft",
        name: "Show subnav on left",
        type: "Boolean",
        localized: false,
        required: false,
        validations: [],
        disabled: false,
        omitted: false,
      },
    ],
  },
  {
    sys: {
      space: { sys: { type: "Link", linkType: "Space", id: "xny2w179f4ki" } },
      id: "featureSpotlightVertical",
      type: "ContentType",
      createdAt: "2019-03-07T19:45:29.277Z",
      updatedAt: "2019-03-07T19:45:29.711Z",
      environment: { sys: { id: "master", type: "Link", linkType: "Environment" } },
      publishedVersion: 1,
      publishedAt: "2019-03-07T19:45:29.711Z",
      firstPublishedAt: "2019-03-07T19:45:29.710Z",
      createdBy: {
        sys: { type: "Link", linkType: "User", id: "6FAPbSCI8Jbv7XzNo2p5CP" },
      },
      updatedBy: {
        sys: { type: "Link", linkType: "User", id: "6FAPbSCI8Jbv7XzNo2p5CP" },
      },
      publishedCounter: 1,
      version: 2,
      publishedBy: {
        sys: { type: "Link", linkType: "User", id: "6FAPbSCI8Jbv7XzNo2p5CP" },
      },
    },
    displayField: "heading",
    name: "Feature Spotlight (Vertical)",
    description:
      "Feature Spotlight with a simple, vertically-stacked layout. Only a heading and image are required, eyebrow and subheading are optional and may be used together if desired.",
    fields: [
      {
        id: "heading",
        name: "Heading",
        type: "Symbol",
        localized: false,
        required: true,
        validations: [],
        disabled: false,
        omitted: false,
      },
      {
        id: "eyebrow",
        name: "Eyebrow",
        type: "Symbol",
        localized: false,
        required: false,
        validations: [],
        disabled: false,
        omitted: false,
      },
      {
        id: "subheading",
        name: "Subheading",
        type: "Symbol",
        localized: false,
        required: false,
        validations: [],
        disabled: false,
        omitted: false,
      },
      {
        id: "cta",
        name: "CTA",
        type: "Link",
        localized: false,
        required: false,
        validations: [{ linkContentType: ["ctaLink"] }],
        disabled: false,
        omitted: false,
        linkType: "Entry",
      },
      {
        id: "image",
        name: "Image",
        type: "Link",
        localized: false,
        required: true,
        validations: [{ linkMimetypeGroup: ["image"] }],
        disabled: false,
        omitted: false,
        linkType: "Asset",
      },
      {
        id: "arrowOnRight",
        name: "Arrow on Right?",
        type: "Boolean",
        localized: false,
        required: false,
        validations: [],
        disabled: false,
        omitted: false,
      },
      {
        id: "backgroundColor",
        name: "Background Color",
        type: "Symbol",
        localized: false,
        required: false,
        validations: [{ in: ["Coral", "Tan", "Teal", "Yellow", "White"] }],
        disabled: false,
        omitted: false,
      },
    ],
  },
  {
    sys: {
      space: { sys: { type: "Link", linkType: "Space", id: "xny2w179f4ki" } },
      id: "securityFeature",
      type: "ContentType",
      createdAt: "2019-01-03T23:20:41.832Z",
      updatedAt: "2019-01-15T00:09:02.427Z",
      environment: { sys: { id: "master", type: "Link", linkType: "Environment" } },
      publishedVersion: 5,
      publishedAt: "2019-01-15T00:09:02.427Z",
      firstPublishedAt: "2019-01-03T23:20:42.224Z",
      createdBy: {
        sys: { type: "Link", linkType: "User", id: "04Z9KRmPanYsqyiqFoU1om" },
      },
      updatedBy: {
        sys: { type: "Link", linkType: "User", id: "04Z9KRmPanYsqyiqFoU1om" },
      },
      publishedCounter: 3,
      version: 6,
      publishedBy: {
        sys: { type: "Link", linkType: "User", id: "04Z9KRmPanYsqyiqFoU1om" },
      },
    },
    displayField: "title",
    name: "Security Feature",
    description: "",
    fields: [
      {
        id: "title",
        name: "Title",
        type: "Symbol",
        localized: true,
        required: true,
        validations: [],
        disabled: false,
        omitted: false,
      },
      {
        id: "description",
        name: "Description",
        type: "RichText",
        localized: true,
        required: true,
        validations: [
          { nodes: {} },
          {
            enabledMarks: ["bold", "italic", "underline"],
            message: "Only bold, italic, and underline marks are allowed",
          },
          { enabledNodeTypes: ["hyperlink"], message: "Only link to Url nodes are allowed" },
        ],
        disabled: false,
        omitted: false,
      },
    ],
  },
  {
    sys: {
      space: { sys: { type: "Link", linkType: "Space", id: "xny2w179f4ki" } },
      id: "price",
      type: "ContentType",
      createdAt: "2019-02-08T00:40:13.063Z",
      updatedAt: "2019-02-08T00:40:13.379Z",
      environment: { sys: { id: "master", type: "Link", linkType: "Environment" } },
      publishedVersion: 1,
      publishedAt: "2019-02-08T00:40:13.379Z",
      firstPublishedAt: "2019-02-08T00:40:13.379Z",
      createdBy: {
        sys: { type: "Link", linkType: "User", id: "04Z9KRmPanYsqyiqFoU1om" },
      },
      updatedBy: {
        sys: { type: "Link", linkType: "User", id: "04Z9KRmPanYsqyiqFoU1om" },
      },
      publishedCounter: 1,
      version: 2,
      publishedBy: {
        sys: { type: "Link", linkType: "User", id: "04Z9KRmPanYsqyiqFoU1om" },
      },
    },
    displayField: "product",
    name: "Price",
    description: "",
    fields: [
      {
        id: "amount",
        name: "Amount",
        type: "Number",
        localized: false,
        required: true,
        validations: [],
        disabled: false,
        omitted: false,
      },
      {
        id: "product",
        name: "Product",
        type: "Symbol",
        localized: false,
        required: true,
        validations: [],
        disabled: false,
        omitted: false,
      },
      {
        id: "currency",
        name: "Currency",
        type: "Symbol",
        localized: false,
        required: true,
        validations: [],
        disabled: false,
        omitted: false,
      },
    ],
  },
  {
    sys: {
      space: { sys: { type: "Link", linkType: "Space", id: "xny2w179f4ki" } },
      id: "featureSpotlight",
      type: "ContentType",
      createdAt: "2019-03-06T00:45:23.235Z",
      updatedAt: "2019-03-06T18:07:03.069Z",
      environment: { sys: { id: "master", type: "Link", linkType: "Environment" } },
      publishedVersion: 5,
      publishedAt: "2019-03-06T18:07:03.069Z",
      firstPublishedAt: "2019-03-06T00:45:23.583Z",
      createdBy: {
        sys: { type: "Link", linkType: "User", id: "3ydnlNuap950mQsaT0TzKZ" },
      },
      updatedBy: {
        sys: { type: "Link", linkType: "User", id: "3ydnlNuap950mQsaT0TzKZ" },
      },
      publishedCounter: 3,
      version: 6,
      publishedBy: {
        sys: { type: "Link", linkType: "User", id: "3ydnlNuap950mQsaT0TzKZ" },
      },
    },
    displayField: "heading",
    name: "Feature Spotlight",
    description:
      "The Feature Spotlight component introduces a new product feature by pairing a snapshot and an associated explanation",
    fields: [
      {
        id: "eyebrow",
        name: "Eyebrow",
        type: "Symbol",
        localized: false,
        required: false,
        validations: [],
        disabled: false,
        omitted: false,
      },
      {
        id: "heading",
        name: "Heading",
        type: "Symbol",
        localized: false,
        required: true,
        validations: [],
        disabled: false,
        omitted: false,
      },
      {
        id: "subheading",
        name: "Subheading",
        type: "Symbol",
        localized: false,
        required: false,
        validations: [],
        disabled: false,
        omitted: false,
      },
      {
        id: "productImage",
        name: "Product Image",
        type: "Link",
        localized: false,
        required: true,
        validations: [{ linkMimetypeGroup: ["image"] }],
        disabled: false,
        omitted: false,
        linkType: "Asset",
      },
      {
        id: "icon",
        name: "Icon",
        type: "Link",
        localized: false,
        required: false,
        validations: [{ linkMimetypeGroup: ["image"] }],
        disabled: false,
        omitted: false,
        linkType: "Asset",
      },
      {
        id: "bgColor",
        name: "Background Color",
        type: "Symbol",
        localized: false,
        required: true,
        validations: [{ in: ["Tan", "Teal", "Coral", "Yellow", "White"] }],
        disabled: false,
        omitted: false,
      },
      {
        id: "cta",
        name: "CTA",
        type: "Link",
        localized: false,
        required: false,
        validations: [{ linkContentType: ["ctaLink"] }],
        disabled: false,
        omitted: false,
        linkType: "Entry",
      },
      {
        id: "imageSide",
        name: "Image side",
        type: "Boolean",
        localized: false,
        required: true,
        validations: [],
        disabled: false,
        omitted: false,
      },
    ],
  },
  {
    sys: {
      space: { sys: { type: "Link", linkType: "Space", id: "xny2w179f4ki" } },
      id: "crosslinkCard",
      type: "ContentType",
      createdAt: "2019-02-12T23:17:43.100Z",
      updatedAt: "2019-02-27T00:18:49.909Z",
      environment: { sys: { id: "master", type: "Link", linkType: "Environment" } },
      publishedVersion: 7,
      publishedAt: "2019-02-27T00:18:49.909Z",
      firstPublishedAt: "2019-02-12T23:17:43.502Z",
      createdBy: {
        sys: { type: "Link", linkType: "User", id: "3ypfTkhVi28ATJHO2MIpS7" },
      },
      updatedBy: {
        sys: { type: "Link", linkType: "User", id: "3ypfTkhVi28ATJHO2MIpS7" },
      },
      publishedCounter: 4,
      version: 8,
      publishedBy: {
        sys: { type: "Link", linkType: "User", id: "3ypfTkhVi28ATJHO2MIpS7" },
      },
    },
    displayField: "title",
    name: "Crosslink Card",
    description:
      "Cards displaying either app integrations or Intercom features/products. They direct to different Intercom.com pages or direct to external links.",
    fields: [
      {
        id: "title",
        name: "Title",
        type: "Symbol",
        localized: false,
        required: true,
        validations: [],
        disabled: false,
        omitted: false,
      },
      {
        id: "bodyText",
        name: "Body Text",
        type: "Symbol",
        localized: false,
        required: true,
        validations: [],
        disabled: false,
        omitted: false,
      },
      {
        id: "icon",
        name: "Icon",
        type: "Link",
        localized: false,
        required: false,
        validations: [{ linkMimetypeGroup: ["image"] }],
        disabled: false,
        omitted: false,
        linkType: "Asset",
      },
      {
        id: "cta",
        name: "CTA",
        type: "Link",
        localized: false,
        required: false,
        validations: [{ linkContentType: ["ctaLink"] }],
        disabled: false,
        omitted: false,
        linkType: "Entry",
      },
      {
        id: "cardColor",
        name: "Card Color",
        type: "Symbol",
        localized: false,
        required: true,
        validations: [{ in: ["Blue", "Coral", "Tan", "Teal", "Yellow", "Violet"] }],
        disabled: false,
        omitted: false,
      },
    ],
  },
  {
    sys: {
      space: { sys: { type: "Link", linkType: "Space", id: "xny2w179f4ki" } },
      id: "navigation",
      type: "ContentType",
      createdAt: "2019-01-10T05:58:41.790Z",
      updatedAt: "2019-01-23T20:55:31.342Z",
      environment: { sys: { id: "master", type: "Link", linkType: "Environment" } },
      publishedVersion: 17,
      publishedAt: "2019-01-23T20:55:31.342Z",
      firstPublishedAt: "2019-01-10T05:58:42.205Z",
      createdBy: {
        sys: { type: "Link", linkType: "User", id: "04Z9KRmPanYsqyiqFoU1om" },
      },
      updatedBy: {
        sys: { type: "Link", linkType: "User", id: "04Z9KRmPanYsqyiqFoU1om" },
      },
      publishedCounter: 9,
      version: 18,
      publishedBy: {
        sys: { type: "Link", linkType: "User", id: "04Z9KRmPanYsqyiqFoU1om" },
      },
    },
    displayField: "title",
    name: "Navigation",
    description: "",
    fields: [
      {
        id: "title",
        name: "Title",
        type: "Symbol",
        localized: false,
        required: false,
        validations: [],
        disabled: false,
        omitted: false,
      },
      {
        id: "topLevelItems",
        name: "Top Level Items",
        type: "Array",
        localized: false,
        required: true,
        validations: [],
        disabled: false,
        omitted: false,
        items: {
          type: "Link",
          validations: [{ linkContentType: ["navigationTopLevelItem"] }],
          linkType: "Entry",
        },
      },
      {
        id: "signupCta",
        name: "Signup CTA",
        type: "Link",
        localized: false,
        required: false,
        validations: [{ linkContentType: ["signupCta"] }],
        disabled: false,
        omitted: false,
        linkType: "Entry",
      },
    ],
  },
  {
    sys: {
      space: { sys: { type: "Link", linkType: "Space", id: "xny2w179f4ki" } },
      id: "logoParty",
      type: "ContentType",
      createdAt: "2019-03-04T21:36:38.361Z",
      updatedAt: "2019-03-04T21:42:56.099Z",
      environment: { sys: { id: "master", type: "Link", linkType: "Environment" } },
      publishedVersion: 3,
      publishedAt: "2019-03-04T21:42:56.099Z",
      firstPublishedAt: "2019-03-04T21:36:38.692Z",
      createdBy: {
        sys: { type: "Link", linkType: "User", id: "3ypfTkhVi28ATJHO2MIpS7" },
      },
      updatedBy: {
        sys: { type: "Link", linkType: "User", id: "3ypfTkhVi28ATJHO2MIpS7" },
      },
      publishedCounter: 2,
      version: 4,
      publishedBy: {
        sys: { type: "Link", linkType: "User", id: "3ypfTkhVi28ATJHO2MIpS7" },
      },
    },
    displayField: "heading",
    name: "Logo Party",
    description:
      "Logo display either displaying Intercom's customers or Apps and Integrations. Minimum of 5. Maximum of 15.",
    fields: [
      {
        id: "heading",
        name: "Heading",
        type: "Symbol",
        localized: false,
        required: true,
        validations: [],
        disabled: false,
        omitted: false,
      },
      {
        id: "subheading",
        name: "Subheading",
        type: "Symbol",
        localized: false,
        required: false,
        validations: [],
        disabled: false,
        omitted: false,
      },
      {
        id: "bgColor",
        name: "Background Color",
        type: "Symbol",
        localized: false,
        required: true,
        validations: [{ in: ["Coral", "Tan", "Teal", "White", "Yellow"] }],
        disabled: false,
        omitted: false,
      },
      {
        id: "logos",
        name: "Logos",
        type: "Array",
        localized: false,
        required: true,
        validations: [{ size: { min: 5, max: 15 } }],
        disabled: false,
        omitted: false,
        items: {
          type: "Link",
          validations: [{ linkContentType: ["logo"] }],
          linkType: "Entry",
        },
      },
      {
        id: "cta",
        name: "CTA",
        type: "Link",
        localized: false,
        required: false,
        validations: [{ linkContentType: ["ctaLink"] }],
        disabled: false,
        omitted: false,
        linkType: "Entry",
      },
    ],
  },
  {
    sys: {
      space: { sys: { type: "Link", linkType: "Space", id: "xny2w179f4ki" } },
      id: "testimonialMiniCard",
      type: "ContentType",
      createdAt: "2019-02-19T22:34:46.304Z",
      updatedAt: "2019-02-20T19:03:42.351Z",
      environment: { sys: { id: "master", type: "Link", linkType: "Environment" } },
      publishedVersion: 3,
      publishedAt: "2019-02-20T19:03:42.351Z",
      firstPublishedAt: "2019-02-19T22:34:46.807Z",
      createdBy: {
        sys: { type: "Link", linkType: "User", id: "3ydnlNuap950mQsaT0TzKZ" },
      },
      updatedBy: {
        sys: { type: "Link", linkType: "User", id: "3ydnlNuap950mQsaT0TzKZ" },
      },
      publishedCounter: 2,
      version: 4,
      publishedBy: {
        sys: { type: "Link", linkType: "User", id: "3ydnlNuap950mQsaT0TzKZ" },
      },
    },
    displayField: "companyName",
    name: "Testimonial Mini Card",
    description:
      "A small testimonial to be repeated in the Mini Testimonials/TestimonialMini component",
    fields: [
      {
        id: "quote",
        name: "Quote",
        type: "Symbol",
        localized: false,
        required: true,
        validations: [],
        disabled: false,
        omitted: false,
      },
      {
        id: "name",
        name: "Name",
        type: "Symbol",
        localized: false,
        required: true,
        validations: [],
        disabled: false,
        omitted: false,
      },
      {
        id: "jobTitle",
        name: "Job Title",
        type: "Symbol",
        localized: false,
        required: true,
        validations: [],
        disabled: false,
        omitted: false,
      },
      {
        id: "companyName",
        name: "Company Name",
        type: "Symbol",
        localized: false,
        required: true,
        validations: [],
        disabled: false,
        omitted: false,
      },
      {
        id: "companyLogo",
        name: "Company Logo",
        type: "Link",
        localized: false,
        required: true,
        validations: [{ linkMimetypeGroup: ["image"] }],
        disabled: false,
        omitted: false,
        linkType: "Asset",
      },
      {
        id: "portrait",
        name: "Portrait",
        type: "Link",
        localized: false,
        required: true,
        validations: [{ linkMimetypeGroup: ["image"] }],
        disabled: false,
        omitted: false,
        linkType: "Asset",
      },
      {
        id: "externalLink",
        name: "External Link",
        type: "Symbol",
        localized: false,
        required: false,
        validations: [
          {
            regexp: {
              pattern: "^(ftp|http|https)://(w+:{0,1}w*@)?(S+)(:[0-9]+)?(/|/([w#!:.?+=&%@!-/]))?$",
            },
          },
        ],
        disabled: false,
        omitted: false,
      },
    ],
  },
  {
    sys: {
      space: { sys: { type: "Link", linkType: "Space", id: "xny2w179f4ki" } },
      id: "navigationSection",
      type: "ContentType",
      createdAt: "2019-01-10T05:59:45.347Z",
      updatedAt: "2019-01-10T06:42:33.925Z",
      environment: { sys: { id: "master", type: "Link", linkType: "Environment" } },
      publishedVersion: 5,
      publishedAt: "2019-01-10T06:42:33.924Z",
      firstPublishedAt: "2019-01-10T05:59:45.802Z",
      createdBy: {
        sys: { type: "Link", linkType: "User", id: "04Z9KRmPanYsqyiqFoU1om" },
      },
      updatedBy: {
        sys: { type: "Link", linkType: "User", id: "04Z9KRmPanYsqyiqFoU1om" },
      },
      publishedCounter: 3,
      version: 6,
      publishedBy: {
        sys: { type: "Link", linkType: "User", id: "04Z9KRmPanYsqyiqFoU1om" },
      },
    },
    displayField: "title",
    name: "Navigation Section",
    description: "",
    fields: [
      {
        id: "title",
        name: "Title",
        type: "Symbol",
        localized: false,
        required: false,
        validations: [],
        disabled: false,
        omitted: false,
      },
      {
        id: "items",
        name: "Items",
        type: "Array",
        localized: false,
        required: true,
        validations: [],
        disabled: false,
        omitted: false,
        items: {
          type: "Link",
          validations: [{ linkContentType: ["navigationItem"] }],
          linkType: "Entry",
        },
      },
    ],
  },
  {
    sys: {
      space: { sys: { type: "Link", linkType: "Space", id: "xny2w179f4ki" } },
      id: "cardList",
      type: "ContentType",
      createdAt: "2019-02-12T23:18:48.595Z",
      updatedAt: "2019-02-27T00:17:36.816Z",
      environment: { sys: { id: "master", type: "Link", linkType: "Environment" } },
      publishedVersion: 5,
      publishedAt: "2019-02-27T00:17:36.816Z",
      firstPublishedAt: "2019-02-12T23:18:48.984Z",
      createdBy: {
        sys: { type: "Link", linkType: "User", id: "3ypfTkhVi28ATJHO2MIpS7" },
      },
      updatedBy: {
        sys: { type: "Link", linkType: "User", id: "3ypfTkhVi28ATJHO2MIpS7" },
      },
      publishedCounter: 3,
      version: 6,
      publishedBy: {
        sys: { type: "Link", linkType: "User", id: "3ypfTkhVi28ATJHO2MIpS7" },
      },
    },
    displayField: "headline",
    name: "Card List",
    description:
      "Can be 1, 2, or 3 across. Type size is variable based on how many are in a row. Cards displaying either app integrations or Intercom features/products. They open up to modals (such as on the app store), direct to different Intercom.com pages, or direct to external links. ",
    fields: [
      {
        id: "headline",
        name: "Headline",
        type: "Symbol",
        localized: true,
        required: false,
        validations: [],
        disabled: false,
        omitted: false,
      },
      {
        id: "cardColor",
        name: "Card Color",
        type: "Symbol",
        localized: false,
        required: true,
        validations: [{ in: ["Blue", "Coral", "Tan", "Teal", "Yellow", "Violet"] }],
        disabled: false,
        omitted: false,
      },
      {
        id: "footnote",
        name: "Footnote",
        type: "Symbol",
        localized: false,
        required: false,
        validations: [],
        disabled: false,
        omitted: false,
      },
      {
        id: "cards",
        name: "Cards",
        type: "Array",
        localized: false,
        required: true,
        validations: [],
        disabled: false,
        omitted: false,
        items: {
          type: "Link",
          validations: [{ linkContentType: ["crosslinkCard"] }],
          linkType: "Entry",
        },
      },
    ],
  },
  {
    sys: {
      space: { sys: { type: "Link", linkType: "Space", id: "xny2w179f4ki" } },
      id: "gatedContent",
      type: "ContentType",
      createdAt: "2019-03-05T21:52:39.115Z",
      updatedAt: "2019-03-05T21:54:03.582Z",
      environment: { sys: { id: "master", type: "Link", linkType: "Environment" } },
      publishedVersion: 3,
      publishedAt: "2019-03-05T21:54:03.582Z",
      firstPublishedAt: "2019-03-05T21:52:39.415Z",
      createdBy: {
        sys: { type: "Link", linkType: "User", id: "6FAPbSCI8Jbv7XzNo2p5CP" },
      },
      updatedBy: {
        sys: { type: "Link", linkType: "User", id: "6FAPbSCI8Jbv7XzNo2p5CP" },
      },
      publishedCounter: 2,
      version: 4,
      publishedBy: {
        sys: { type: "Link", linkType: "User", id: "6FAPbSCI8Jbv7XzNo2p5CP" },
      },
    },
    displayField: "heading",
    name: "Gated Content CTA",
    description:
      "Direct users to related gated content from marketing pages. Ideally, captures email address, which then gives user access to the e-book download.",
    fields: [
      {
        id: "heading",
        name: "Heading",
        type: "Symbol",
        localized: false,
        required: true,
        validations: [],
        disabled: false,
        omitted: false,
      },
      {
        id: "subheading",
        name: "Subheading",
        type: "Symbol",
        localized: false,
        required: true,
        validations: [],
        disabled: false,
        omitted: false,
      },
      {
        id: "bgColor",
        name: "Background Color",
        type: "Symbol",
        localized: false,
        required: true,
        validations: [{ in: ["Yellow", "Teal", "Tan", "Coral"] }],
        disabled: false,
        omitted: false,
      },
      {
        id: "submitButtonText",
        name: "Submit Button Text",
        type: "Symbol",
        localized: false,
        required: true,
        validations: [{ size: { max: 32 } }],
        disabled: false,
        omitted: false,
      },
    ],
  },
  {
    sys: {
      space: { sys: { type: "Link", linkType: "Space", id: "xny2w179f4ki" } },
      id: "heroEmailCapture",
      type: "ContentType",
      createdAt: "2019-03-05T20:58:02.854Z",
      updatedAt: "2019-03-05T20:58:03.164Z",
      environment: { sys: { id: "master", type: "Link", linkType: "Environment" } },
      publishedVersion: 1,
      publishedAt: "2019-03-05T20:58:03.164Z",
      firstPublishedAt: "2019-03-05T20:58:03.164Z",
      createdBy: {
        sys: { type: "Link", linkType: "User", id: "3ydnlNuap950mQsaT0TzKZ" },
      },
      updatedBy: {
        sys: { type: "Link", linkType: "User", id: "3ydnlNuap950mQsaT0TzKZ" },
      },
      publishedCounter: 1,
      version: 2,
      publishedBy: {
        sys: { type: "Link", linkType: "User", id: "3ydnlNuap950mQsaT0TzKZ" },
      },
    },
    displayField: "headline",
    name: "Hero Email Capture",
    description:
      "A hero greeting to the user with a large product benefit, subtext and an input field to capture email.",
    fields: [
      {
        id: "eyebrow",
        name: "Eyebrow",
        type: "Symbol",
        localized: false,
        required: false,
        validations: [],
        disabled: false,
        omitted: false,
      },
      {
        id: "headline",
        name: "Headline",
        type: "Symbol",
        localized: false,
        required: true,
        validations: [{ size: { max: 80 } }],
        disabled: false,
        omitted: false,
      },
      {
        id: "subheading",
        name: "Subheading",
        type: "Symbol",
        localized: false,
        required: false,
        validations: [],
        disabled: false,
        omitted: false,
      },
      {
        id: "leftAlign",
        name: "Left Align",
        type: "Boolean",
        localized: false,
        required: true,
        validations: [],
        disabled: false,
        omitted: false,
      },
      {
        id: "bgImage",
        name: "Background Image",
        type: "Link",
        localized: false,
        required: false,
        validations: [{ linkMimetypeGroup: ["image"] }],
        disabled: false,
        omitted: false,
        linkType: "Asset",
      },
      {
        id: "checkmarks",
        name: "Checkmarks",
        type: "Array",
        localized: false,
        required: false,
        validations: [{ size: { min: 1, max: 1 } }],
        disabled: false,
        omitted: false,
        items: {
          type: "Link",
          validations: [{ linkContentType: ["checkmarks"] }],
          linkType: "Entry",
        },
      },
    ],
  },
  {
    sys: {
      space: { sys: { type: "Link", linkType: "Space", id: "xny2w179f4ki" } },
      id: "jumbotronHeader",
      type: "ContentType",
      createdAt: "2019-01-07T23:55:27.569Z",
      updatedAt: "2019-01-11T17:36:50.163Z",
      environment: { sys: { id: "master", type: "Link", linkType: "Environment" } },
      publishedVersion: 3,
      publishedAt: "2019-01-11T17:36:50.163Z",
      firstPublishedAt: "2019-01-07T23:55:27.915Z",
      createdBy: {
        sys: { type: "Link", linkType: "User", id: "04Z9KRmPanYsqyiqFoU1om" },
      },
      updatedBy: {
        sys: { type: "Link", linkType: "User", id: "04Z9KRmPanYsqyiqFoU1om" },
      },
      publishedCounter: 2,
      version: 4,
      publishedBy: {
        sys: { type: "Link", linkType: "User", id: "04Z9KRmPanYsqyiqFoU1om" },
      },
    },
    displayField: null,
    name: "Jumbotron Header",
    description: "",
    fields: [
      {
        id: "content",
        name: "Content",
        type: "RichText",
        localized: true,
        required: true,
        validations: [{ nodes: {} }],
        disabled: false,
        omitted: false,
      },
    ],
  },
  {
    sys: {
      space: { sys: { type: "Link", linkType: "Space", id: "xny2w179f4ki" } },
      id: "ctaLink",
      type: "ContentType",
      createdAt: "2019-02-12T23:16:09.520Z",
      updatedAt: "2019-02-12T23:16:09.855Z",
      environment: { sys: { id: "master", type: "Link", linkType: "Environment" } },
      publishedVersion: 1,
      publishedAt: "2019-02-12T23:16:09.855Z",
      firstPublishedAt: "2019-02-12T23:16:09.855Z",
      createdBy: {
        sys: { type: "Link", linkType: "User", id: "3ypfTkhVi28ATJHO2MIpS7" },
      },
      updatedBy: {
        sys: { type: "Link", linkType: "User", id: "3ypfTkhVi28ATJHO2MIpS7" },
      },
      publishedCounter: 1,
      version: 2,
      publishedBy: {
        sys: { type: "Link", linkType: "User", id: "3ypfTkhVi28ATJHO2MIpS7" },
      },
    },
    displayField: "label",
    name: "CTA Link",
    description: "",
    fields: [
      {
        id: "label",
        name: "Label",
        type: "Symbol",
        localized: false,
        required: true,
        validations: [],
        disabled: false,
        omitted: false,
      },
      {
        id: "url",
        name: "URL",
        type: "Symbol",
        localized: false,
        required: true,
        validations: [],
        disabled: false,
        omitted: false,
      },
      {
        id: "color",
        name: "Color",
        type: "Symbol",
        localized: false,
        required: true,
        validations: [{ in: ["Black", "White", "Teal", "Tan"] }],
        disabled: false,
        omitted: false,
      },
      {
        id: "openInNewWindow",
        name: "Open in New Window",
        type: "Boolean",
        localized: false,
        required: true,
        validations: [],
        disabled: false,
        omitted: false,
      },
    ],
  },
  {
    sys: {
      space: { sys: { type: "Link", linkType: "Space", id: "xny2w179f4ki" } },
      id: "layout",
      type: "ContentType",
      createdAt: "2019-01-15T20:41:34.152Z",
      updatedAt: "2019-01-15T21:16:08.409Z",
      environment: { sys: { id: "master", type: "Link", linkType: "Environment" } },
      publishedVersion: 7,
      publishedAt: "2019-01-15T21:16:08.409Z",
      firstPublishedAt: "2019-01-15T20:41:34.580Z",
      createdBy: {
        sys: { type: "Link", linkType: "User", id: "04Z9KRmPanYsqyiqFoU1om" },
      },
      updatedBy: {
        sys: { type: "Link", linkType: "User", id: "04Z9KRmPanYsqyiqFoU1om" },
      },
      publishedCounter: 4,
      version: 8,
      publishedBy: {
        sys: { type: "Link", linkType: "User", id: "04Z9KRmPanYsqyiqFoU1om" },
      },
    },
    displayField: "name",
    name: "Layout",
    description: "",
    fields: [
      {
        id: "name",
        name: "Name",
        type: "Symbol",
        localized: false,
        required: true,
        validations: [],
        disabled: false,
        omitted: false,
      },
      {
        id: "navigation",
        name: "Navigation",
        type: "Link",
        localized: false,
        required: true,
        validations: [{ linkContentType: ["navigation"] }],
        disabled: false,
        omitted: false,
        linkType: "Entry",
      },
      {
        id: "footer",
        name: "Footer",
        type: "Link",
        localized: false,
        required: true,
        validations: [{ linkContentType: ["footer"] }],
        disabled: false,
        omitted: false,
        linkType: "Entry",
      },
    ],
  },
  {
    sys: {
      space: { sys: { type: "Link", linkType: "Space", id: "xny2w179f4ki" } },
      id: "logo",
      type: "ContentType",
      createdAt: "2019-03-04T21:38:48.170Z",
      updatedAt: "2019-03-04T21:38:48.529Z",
      environment: { sys: { id: "master", type: "Link", linkType: "Environment" } },
      publishedVersion: 1,
      publishedAt: "2019-03-04T21:38:48.529Z",
      firstPublishedAt: "2019-03-04T21:38:48.529Z",
      createdBy: {
        sys: { type: "Link", linkType: "User", id: "3ypfTkhVi28ATJHO2MIpS7" },
      },
      updatedBy: {
        sys: { type: "Link", linkType: "User", id: "3ypfTkhVi28ATJHO2MIpS7" },
      },
      publishedCounter: 1,
      version: 2,
      publishedBy: {
        sys: { type: "Link", linkType: "User", id: "3ypfTkhVi28ATJHO2MIpS7" },
      },
    },
    displayField: "companyName",
    name: "Logo",
    description: "Company logo and alt text to be used in logo party",
    fields: [
      {
        id: "logoUrl",
        name: "Company Logo",
        type: "Link",
        localized: false,
        required: true,
        validations: [{ linkMimetypeGroup: ["image"] }],
        disabled: false,
        omitted: false,
        linkType: "Asset",
      },
      {
        id: "companyName",
        name: "Company Name",
        type: "Symbol",
        localized: false,
        required: true,
        validations: [],
        disabled: false,
        omitted: false,
      },
    ],
  },
  {
    sys: {
      space: { sys: { type: "Link", linkType: "Space", id: "xny2w179f4ki" } },
      id: "securityFeaturesSection",
      type: "ContentType",
      createdAt: "2019-01-03T23:23:24.222Z",
      updatedAt: "2019-01-23T20:39:33.973Z",
      environment: { sys: { id: "master", type: "Link", linkType: "Environment" } },
      publishedVersion: 5,
      publishedAt: "2019-01-23T20:39:33.973Z",
      firstPublishedAt: "2019-01-03T23:23:24.551Z",
      createdBy: {
        sys: { type: "Link", linkType: "User", id: "04Z9KRmPanYsqyiqFoU1om" },
      },
      updatedBy: {
        sys: { type: "Link", linkType: "User", id: "04Z9KRmPanYsqyiqFoU1om" },
      },
      publishedCounter: 3,
      version: 6,
      publishedBy: {
        sys: { type: "Link", linkType: "User", id: "04Z9KRmPanYsqyiqFoU1om" },
      },
    },
    displayField: "title",
    name: "Security Features Section",
    description: "",
    fields: [
      {
        id: "title",
        name: "Title",
        type: "Symbol",
        localized: false,
        required: true,
        validations: [],
        disabled: false,
        omitted: false,
      },
      {
        id: "gdprButtonLabel",
        name: "GDPR Button Label",
        type: "Symbol",
        localized: true,
        required: true,
        validations: [],
        disabled: false,
        omitted: false,
      },
      {
        id: "featureCategories",
        name: "Feature categories",
        type: "Array",
        localized: false,
        required: true,
        validations: [],
        disabled: false,
        omitted: false,
        items: {
          type: "Link",
          validations: [{ linkContentType: ["securityFeatureCategory"] }],
          linkType: "Entry",
        },
      },
    ],
  },
  {
    sys: {
      space: { sys: { type: "Link", linkType: "Space", id: "xny2w179f4ki" } },
      id: "footerSection",
      type: "ContentType",
      createdAt: "2019-01-09T20:43:26.172Z",
      updatedAt: "2019-01-15T17:42:10.412Z",
      environment: { sys: { id: "master", type: "Link", linkType: "Environment" } },
      publishedVersion: 7,
      publishedAt: "2019-01-15T17:42:10.412Z",
      firstPublishedAt: "2019-01-09T20:43:26.712Z",
      createdBy: {
        sys: { type: "Link", linkType: "User", id: "04Z9KRmPanYsqyiqFoU1om" },
      },
      updatedBy: {
        sys: { type: "Link", linkType: "User", id: "04Z9KRmPanYsqyiqFoU1om" },
      },
      publishedCounter: 4,
      version: 8,
      publishedBy: {
        sys: { type: "Link", linkType: "User", id: "04Z9KRmPanYsqyiqFoU1om" },
      },
    },
    displayField: "title",
    name: "Footer Section",
    description: "",
    fields: [
      {
        id: "title",
        name: "Title",
        type: "Symbol",
        localized: true,
        required: true,
        validations: [],
        disabled: false,
        omitted: false,
      },
      {
        id: "content",
        name: "Content",
        type: "RichText",
        localized: true,
        required: true,
        validations: [{ nodes: {} }],
        disabled: false,
        omitted: false,
      },
    ],
  },
  {
    sys: {
      space: { sys: { type: "Link", linkType: "Space", id: "xny2w179f4ki" } },
      id: "marketoForm",
      type: "ContentType",
      createdAt: "2019-03-05T01:32:14.926Z",
      updatedAt: "2019-03-05T01:32:15.698Z",
      environment: { sys: { id: "master", type: "Link", linkType: "Environment" } },
      publishedVersion: 1,
      publishedAt: "2019-03-05T01:32:15.698Z",
      firstPublishedAt: "2019-03-05T01:32:15.698Z",
      createdBy: {
        sys: { type: "Link", linkType: "User", id: "04Z9KRmPanYsqyiqFoU1om" },
      },
      updatedBy: {
        sys: { type: "Link", linkType: "User", id: "04Z9KRmPanYsqyiqFoU1om" },
      },
      publishedCounter: 1,
      version: 2,
      publishedBy: {
        sys: { type: "Link", linkType: "User", id: "04Z9KRmPanYsqyiqFoU1om" },
      },
    },
    displayField: "name",
    name: "Marketo Form",
    description: "Embed a Marketo Form on the page",
    fields: [
      {
        id: "name",
        name: "Name",
        type: "Symbol",
        localized: false,
        required: false,
        validations: [],
        disabled: false,
        omitted: false,
      },
      {
        id: "marketoForm",
        name: "Marketo form",
        type: "Object",
        localized: false,
        required: true,
        validations: [],
        disabled: false,
        omitted: false,
      },
    ],
  },
  {
    sys: {
      space: { sys: { type: "Link", linkType: "Space", id: "xny2w179f4ki" } },
      id: "emailCapture",
      type: "ContentType",
      createdAt: "2019-02-28T18:52:59.001Z",
      updatedAt: "2019-03-01T21:59:06.649Z",
      environment: { sys: { id: "master", type: "Link", linkType: "Environment" } },
      publishedVersion: 3,
      publishedAt: "2019-03-01T21:59:06.649Z",
      firstPublishedAt: "2019-02-28T18:52:59.284Z",
      createdBy: {
        sys: { type: "Link", linkType: "User", id: "3ypfTkhVi28ATJHO2MIpS7" },
      },
      updatedBy: {
        sys: { type: "Link", linkType: "User", id: "3ypfTkhVi28ATJHO2MIpS7" },
      },
      publishedCounter: 2,
      version: 4,
      publishedBy: {
        sys: { type: "Link", linkType: "User", id: "3ypfTkhVi28ATJHO2MIpS7" },
      },
    },
    displayField: "heading",
    name: "Email Capture",
    description: "A general signup/start trial email submission form ",
    fields: [
      {
        id: "heading",
        name: "Heading",
        type: "Symbol",
        localized: false,
        required: true,
        validations: [],
        disabled: false,
        omitted: false,
      },
      {
        id: "eyebrow",
        name: "Eyebrow",
        type: "Symbol",
        localized: false,
        required: false,
        validations: [],
        disabled: false,
        omitted: false,
      },
      {
        id: "fullWidth",
        name: "Full-width",
        type: "Boolean",
        localized: false,
        required: false,
        validations: [],
        disabled: false,
        omitted: false,
      },
      {
        id: "bgColor",
        name: "Background Color",
        type: "Symbol",
        localized: false,
        required: true,
        validations: [{ in: ["Yellow", "Teal"] }],
        disabled: false,
        omitted: false,
      },
      {
        id: "bgImage",
        name: "Background Image",
        type: "Boolean",
        localized: false,
        required: false,
        validations: [],
        disabled: false,
        omitted: false,
      },
      {
        id: "cta",
        name: "CTA",
        type: "Link",
        localized: false,
        required: false,
        validations: [{ linkContentType: ["ctaLink"] }],
        disabled: false,
        omitted: false,
        linkType: "Entry",
      },
      {
        id: "checkmarks",
        name: "Checkmarks",
        type: "Array",
        localized: false,
        required: false,
        validations: [{ size: { min: 1, max: 1 } }],
        disabled: false,
        omitted: false,
        items: {
          type: "Link",
          validations: [{ linkContentType: ["checkmarks"] }],
          linkType: "Entry",
        },
      },
    ],
  },
  {
    sys: {
      space: { sys: { type: "Link", linkType: "Space", id: "xny2w179f4ki" } },
      id: "securityFooter",
      type: "ContentType",
      createdAt: "2019-01-10T00:50:11.016Z",
      updatedAt: "2019-01-14T22:25:09.847Z",
      environment: { sys: { id: "master", type: "Link", linkType: "Environment" } },
      publishedVersion: 3,
      publishedAt: "2019-01-14T22:25:09.847Z",
      firstPublishedAt: "2019-01-10T00:50:11.393Z",
      createdBy: {
        sys: { type: "Link", linkType: "User", id: "04Z9KRmPanYsqyiqFoU1om" },
      },
      updatedBy: {
        sys: { type: "Link", linkType: "User", id: "04Z9KRmPanYsqyiqFoU1om" },
      },
      publishedCounter: 2,
      version: 4,
      publishedBy: {
        sys: { type: "Link", linkType: "User", id: "04Z9KRmPanYsqyiqFoU1om" },
      },
    },
    displayField: "title",
    name: "Security Footer",
    description: "",
    fields: [
      {
        id: "title",
        name: "Title",
        type: "Symbol",
        localized: true,
        required: true,
        validations: [],
        disabled: false,
        omitted: false,
      },
      {
        id: "content",
        name: "Content",
        type: "RichText",
        localized: true,
        required: true,
        validations: [
          { nodes: {} },
          {
            enabledNodeTypes: [
              "heading-1",
              "heading-2",
              "heading-3",
              "heading-4",
              "heading-5",
              "heading-6",
              "ordered-list",
              "unordered-list",
              "hr",
              "blockquote",
              "hyperlink",
              "entry-hyperlink",
              "asset-hyperlink",
            ],
            message:
              "Only heading 1, heading 2, heading 3, heading 4, heading 5, heading 6, ordered list, unordered list, horizontal rule, quote, link to Url, link to entry, and link to asset nodes are allowed",
          },
        ],
        disabled: false,
        omitted: false,
      },
    ],
  },
  {
    sys: {
      space: { sys: { type: "Link", linkType: "Space", id: "xny2w179f4ki" } },
      id: "featureSpotlightCitation",
      type: "ContentType",
      createdAt: "2019-03-07T00:24:48.754Z",
      updatedAt: "2019-03-07T01:22:56.605Z",
      environment: { sys: { id: "master", type: "Link", linkType: "Environment" } },
      publishedVersion: 5,
      publishedAt: "2019-03-07T01:22:56.605Z",
      firstPublishedAt: "2019-03-07T00:24:49.175Z",
      createdBy: {
        sys: { type: "Link", linkType: "User", id: "3ydnlNuap950mQsaT0TzKZ" },
      },
      updatedBy: {
        sys: { type: "Link", linkType: "User", id: "3ydnlNuap950mQsaT0TzKZ" },
      },
      publishedCounter: 3,
      version: 6,
      publishedBy: {
        sys: { type: "Link", linkType: "User", id: "3ydnlNuap950mQsaT0TzKZ" },
      },
    },
    displayField: "heading",
    name: "Feature Spotlight Citation",
    description:
      "A feature benefit is presented but also tells the user why they should consider it important. Education moment; links to a third-party study or resource.",
    fields: [
      {
        id: "heading",
        name: "Heading",
        type: "Symbol",
        localized: false,
        required: true,
        validations: [],
        disabled: false,
        omitted: false,
      },
      {
        id: "eyebrow",
        name: "Eyebrow",
        type: "Symbol",
        localized: false,
        required: false,
        validations: [],
        disabled: false,
        omitted: false,
      },
      {
        id: "subheading",
        name: "Subheading",
        type: "Symbol",
        localized: false,
        required: false,
        validations: [],
        disabled: false,
        omitted: false,
      },
      {
        id: "productImage",
        name: "Product Image",
        type: "Link",
        localized: false,
        required: true,
        validations: [{ linkMimetypeGroup: ["image"] }],
        disabled: false,
        omitted: false,
        linkType: "Asset",
      },
      {
        id: "citationQuote",
        name: "Citation Quote",
        type: "Symbol",
        localized: false,
        required: true,
        validations: [],
        disabled: false,
        omitted: false,
      },
      {
        id: "citationSource",
        name: "Citation Source",
        type: "Symbol",
        localized: false,
        required: true,
        validations: [],
        disabled: false,
        omitted: false,
      },
      {
        id: "citationPublicationTitle",
        name: "Citation Publication Title",
        type: "Symbol",
        localized: false,
        required: true,
        validations: [],
        disabled: false,
        omitted: false,
      },
      {
        id: "citationUrl",
        name: "Citation URL",
        type: "Symbol",
        localized: false,
        required: true,
        validations: [
          {
            regexp: {
              pattern: "^(ftp|http|https)://(w+:{0,1}w*@)?(S+)(:[0-9]+)?(/|/([w#!:.?+=&%@!-/]))?$",
            },
          },
        ],
        disabled: false,
        omitted: false,
      },
      {
        id: "icon",
        name: "Icon",
        type: "Link",
        localized: false,
        required: false,
        validations: [{ linkMimetypeGroup: ["image"] }],
        disabled: false,
        omitted: false,
        linkType: "Asset",
      },
      {
        id: "bgColor",
        name: "Background Color",
        type: "Symbol",
        localized: false,
        required: true,
        validations: [{ in: ["Teal", "Tan", "Coral", "White", "Yellow"] }],
        disabled: false,
        omitted: false,
      },
      {
        id: "imageSide",
        name: "Image Side",
        type: "Boolean",
        localized: false,
        required: true,
        validations: [],
        disabled: false,
        omitted: false,
      },
      {
        id: "cta",
        name: "CTA",
        type: "Link",
        localized: false,
        required: false,
        validations: [{ linkContentType: ["ctaLink"] }],
        disabled: false,
        omitted: false,
        linkType: "Entry",
      },
    ],
  },
  {
    sys: {
      space: { sys: { type: "Link", linkType: "Space", id: "xny2w179f4ki" } },
      id: "featureAnnouncement",
      type: "ContentType",
      createdAt: "2019-02-20T18:20:53.701Z",
      updatedAt: "2019-03-08T19:49:59.928Z",
      environment: { sys: { id: "master", type: "Link", linkType: "Environment" } },
      publishedVersion: 31,
      publishedAt: "2019-03-08T19:49:59.928Z",
      firstPublishedAt: "2019-02-20T18:20:54.132Z",
      createdBy: {
        sys: { type: "Link", linkType: "User", id: "3ydnlNuap950mQsaT0TzKZ" },
      },
      updatedBy: {
        sys: { type: "Link", linkType: "User", id: "3ydnlNuap950mQsaT0TzKZ" },
      },
      publishedCounter: 16,
      version: 32,
      publishedBy: {
        sys: { type: "Link", linkType: "User", id: "3ydnlNuap950mQsaT0TzKZ" },
      },
    },
    displayField: "title",
    name: "Feature Announcement",
    description:
      "Introduces new product feature by pairing a snapshot and an associated explanation. Used to message a new feature or product.",
    fields: [
      {
        id: "description",
        name: "Entry Description",
        type: "Symbol",
        localized: false,
        required: false,
        validations: [],
        disabled: false,
        omitted: true,
      },
      {
        id: "eyebrow",
        name: "Eyebrow",
        type: "Symbol",
        localized: false,
        required: true,
        validations: [],
        disabled: false,
        omitted: false,
      },
      {
        id: "title",
        name: "Title",
        type: "Symbol",
        localized: false,
        required: true,
        validations: [],
        disabled: false,
        omitted: false,
      },
      {
        id: "icon",
        name: "Icon",
        type: "Link",
        localized: false,
        required: false,
        validations: [{ linkMimetypeGroup: ["image"] }],
        disabled: false,
        omitted: false,
        linkType: "Asset",
      },
      {
        id: "image",
        name: "Image",
        type: "Link",
        localized: false,
        required: true,
        validations: [{ linkMimetypeGroup: ["image"] }],
        disabled: false,
        omitted: false,
        linkType: "Asset",
      },
      {
        id: "newSticker",
        name: "Include NEW Animation",
        type: "Boolean",
        localized: false,
        required: false,
        validations: [],
        disabled: false,
        omitted: false,
      },
      {
        id: "flipped",
        name: "Image on left?",
        type: "Boolean",
        localized: false,
        required: false,
        validations: [],
        disabled: false,
        omitted: false,
      },
      {
        id: "bgColor",
        name: "Background Color",
        type: "Symbol",
        localized: false,
        required: true,
        validations: [{ in: ["Tan", "Teal"] }],
        disabled: false,
        omitted: false,
      },
      {
        id: "cta1",
        name: "CTA 1",
        type: "Link",
        localized: false,
        required: true,
        validations: [{ linkContentType: ["ctaLink"] }],
        disabled: false,
        omitted: false,
        linkType: "Entry",
      },
      {
        id: "cta2",
        name: "CTA 2",
        type: "Link",
        localized: false,
        required: false,
        validations: [{ linkContentType: ["ctaLink"] }],
        disabled: false,
        omitted: false,
        linkType: "Entry",
      },
    ],
  },
  {
    sys: {
      space: { sys: { type: "Link", linkType: "Space", id: "xny2w179f4ki" } },
      id: "page",
      type: "ContentType",
      createdAt: "2018-12-19T21:50:33.215Z",
      updatedAt: "2019-03-08T18:48:00.889Z",
      environment: { sys: { id: "master", type: "Link", linkType: "Environment" } },
      publishedVersion: 59,
      publishedAt: "2019-03-08T18:48:00.889Z",
      firstPublishedAt: "2018-12-19T21:50:33.636Z",
      createdBy: {
        sys: { type: "Link", linkType: "User", id: "04Z9KRmPanYsqyiqFoU1om" },
      },
      updatedBy: {
        sys: { type: "Link", linkType: "User", id: "3ypfTkhVi28ATJHO2MIpS7" },
      },
      publishedCounter: 30,
      version: 60,
      publishedBy: {
        sys: { type: "Link", linkType: "User", id: "3ypfTkhVi28ATJHO2MIpS7" },
      },
    },
    displayField: "title",
    name: "Page",
    description: "",
    fields: [
      {
        id: "path",
        name: "Path",
        type: "Symbol",
        localized: false,
        required: true,
        validations: [
          {
            regexp: { pattern: "^[a-z-]+(/[a-z-]+)*$", flags: "" },
            message:
              "This is an invalid path. Paths cannot start with a slash and must contain only lowercase letters, numbers, dashes, and forward slashes.",
          },
        ],
        disabled: false,
        omitted: false,
      },
      {
        id: "title",
        name: "Title",
        type: "Symbol",
        localized: true,
        required: true,
        validations: [],
        disabled: false,
        omitted: false,
      },
      {
        id: "seoMetadata",
        name: "SEO Metadata",
        type: "Link",
        localized: true,
        required: true,
        validations: [{ linkContentType: ["seoMetadata"] }],
        disabled: false,
        omitted: false,
        linkType: "Entry",
      },
      {
        id: "layout",
        name: "Layout",
        type: "Link",
        localized: false,
        required: false,
        validations: [{ linkContentType: ["layout"] }],
        disabled: false,
        omitted: false,
        linkType: "Entry",
      },
      {
        id: "content",
        name: "Content",
        type: "RichText",
        localized: true,
        required: false,
        validations: [
          {
            nodes: {
              "embedded-entry-block": [
                {
                  linkContentType: [
                    "cardList",
                    "complianceLogoPond",
                    "crosslinkCard",
                    "emailCapture",
                    "featureAnnouncement",
                    "featureSpotlight",
                    "featureSpotlightVertical",
                    "featureSpotlightCitation",
                    "footer",
                    "gatedContent",
                    "heroEmailCapture",
                    "jumbotronHeader",
                    "largeTestimonial",
                    "logoParty",
                    "marketoForm",
                    "miniTestimonials",
                    "navigation",
                    "rooflineBanner",
                    "securityFeaturesSection",
                    "securityFooter",
                  ],
                  message:
                    "The component or element that you are trying to add is meant to be embedded inside another component and not included on the page directly.",
                },
              ],
            },
          },
        ],
        disabled: false,
        omitted: false,
      },
    ],
  },
  {
    sys: {
      space: { sys: { type: "Link", linkType: "Space", id: "xny2w179f4ki" } },
      id: "securityFeatureCategory",
      type: "ContentType",
      createdAt: "2019-01-03T23:23:04.058Z",
      updatedAt: "2019-01-23T20:00:30.952Z",
      environment: { sys: { id: "master", type: "Link", linkType: "Environment" } },
      publishedVersion: 11,
      publishedAt: "2019-01-23T20:00:30.952Z",
      firstPublishedAt: "2019-01-03T23:23:04.551Z",
      createdBy: {
        sys: { type: "Link", linkType: "User", id: "04Z9KRmPanYsqyiqFoU1om" },
      },
      updatedBy: {
        sys: { type: "Link", linkType: "User", id: "04Z9KRmPanYsqyiqFoU1om" },
      },
      publishedCounter: 6,
      version: 12,
      publishedBy: {
        sys: { type: "Link", linkType: "User", id: "04Z9KRmPanYsqyiqFoU1om" },
      },
    },
    displayField: "title",
    name: "Security Feature Category",
    description: "",
    fields: [
      {
        id: "icon",
        name: "Icon",
        type: "Link",
        localized: false,
        required: true,
        validations: [{ linkMimetypeGroup: ["image"] }],
        disabled: false,
        omitted: false,
        linkType: "Asset",
      },
      {
        id: "title",
        name: "Title",
        type: "Symbol",
        localized: true,
        required: true,
        validations: [],
        disabled: false,
        omitted: false,
      },
      {
        id: "buttonLabel",
        name: "Button label",
        type: "Symbol",
        localized: true,
        required: true,
        validations: [],
        disabled: false,
        omitted: false,
      },
      {
        id: "features",
        name: "Features",
        type: "Array",
        localized: false,
        required: true,
        validations: [],
        disabled: false,
        omitted: false,
        items: {
          type: "Link",
          validations: [{ linkContentType: ["securityFeature"] }],
          linkType: "Entry",
        },
      },
    ],
  },
  {
    sys: {
      space: { sys: { type: "Link", linkType: "Space", id: "xny2w179f4ki" } },
      id: "footer",
      type: "ContentType",
      createdAt: "2019-01-09T20:44:11.924Z",
      updatedAt: "2019-01-09T20:44:12.368Z",
      environment: { sys: { id: "master", type: "Link", linkType: "Environment" } },
      publishedVersion: 1,
      publishedAt: "2019-01-09T20:44:12.368Z",
      firstPublishedAt: "2019-01-09T20:44:12.368Z",
      createdBy: {
        sys: { type: "Link", linkType: "User", id: "04Z9KRmPanYsqyiqFoU1om" },
      },
      updatedBy: {
        sys: { type: "Link", linkType: "User", id: "04Z9KRmPanYsqyiqFoU1om" },
      },
      publishedCounter: 1,
      version: 2,
      publishedBy: {
        sys: { type: "Link", linkType: "User", id: "04Z9KRmPanYsqyiqFoU1om" },
      },
    },
    displayField: null,
    name: "Footer",
    description: "",
    fields: [
      {
        id: "sections",
        name: "Sections",
        type: "Array",
        localized: false,
        required: true,
        validations: [],
        disabled: false,
        omitted: false,
        items: {
          type: "Link",
          validations: [{ linkContentType: ["footerSection"] }],
          linkType: "Entry",
        },
      },
    ],
  },
  {
    sys: {
      space: { sys: { type: "Link", linkType: "Space", id: "xny2w179f4ki" } },
      id: "seoMetadata",
      type: "ContentType",
      createdAt: "2019-01-16T23:20:09.076Z",
      updatedAt: "2019-03-01T22:58:53.337Z",
      environment: { sys: { id: "master", type: "Link", linkType: "Environment" } },
      publishedVersion: 29,
      publishedAt: "2019-03-01T22:58:53.337Z",
      firstPublishedAt: "2019-01-16T23:20:09.589Z",
      createdBy: {
        sys: { type: "Link", linkType: "User", id: "04Z9KRmPanYsqyiqFoU1om" },
      },
      updatedBy: {
        sys: { type: "Link", linkType: "User", id: "6FAPbSCI8Jbv7XzNo2p5CP" },
      },
      publishedCounter: 15,
      version: 30,
      publishedBy: {
        sys: { type: "Link", linkType: "User", id: "6FAPbSCI8Jbv7XzNo2p5CP" },
      },
    },
    displayField: "metaTitle",
    name: "SEO Metadata",
    description: "",
    fields: [
      {
        id: "metaTitle",
        name: "Meta Title",
        type: "Symbol",
        localized: true,
        required: true,
        validations: [{ size: { max: 60 } }],
        disabled: false,
        omitted: false,
      },
      {
        id: "metaDescription",
        name: "Meta Description",
        type: "Text",
        localized: true,
        required: true,
        validations: [{ size: { max: 160 } }],
        disabled: false,
        omitted: false,
      },
      {
        id: "openGraphTitle",
        name: "OpenGraph Title",
        type: "Symbol",
        localized: true,
        required: true,
        validations: [],
        disabled: false,
        omitted: false,
      },
      {
        id: "openGraphDescription",
        name: "OpenGraph Description",
        type: "Text",
        localized: true,
        required: true,
        validations: [],
        disabled: false,
        omitted: false,
      },
      {
        id: "openGraphImage",
        name: "OpenGraph Image",
        type: "Link",
        localized: true,
        required: true,
        validations: [{ linkMimetypeGroup: ["image"] }],
        disabled: false,
        omitted: false,
        linkType: "Asset",
      },
      {
        id: "metaKeywords",
        name: "Meta Keywords",
        type: "Array",
        localized: false,
        required: true,
        validations: [],
        disabled: false,
        omitted: false,
        items: { type: "Symbol", validations: [] },
      },
      {
        id: "disableCrawling",
        name: "Disable Crawling",
        type: "Boolean",
        localized: false,
        required: true,
        validations: [],
        disabled: false,
        omitted: false,
      },
      {
        id: "metaCanonical",
        name: "Canonical Tag",
        type: "Symbol",
        localized: false,
        required: false,
        validations: [],
        disabled: false,
        omitted: false,
      },
    ],
  },
  {
    sys: {
      space: { sys: { type: "Link", linkType: "Space", id: "xny2w179f4ki" } },
      id: "complianceLogo",
      type: "ContentType",
      createdAt: "2018-12-19T22:32:44.002Z",
      updatedAt: "2019-03-07T17:09:15.741Z",
      environment: { sys: { id: "master", type: "Link", linkType: "Environment" } },
      publishedVersion: 23,
      publishedAt: "2019-03-07T17:09:15.741Z",
      firstPublishedAt: "2018-12-19T22:32:44.424Z",
      createdBy: {
        sys: { type: "Link", linkType: "User", id: "04Z9KRmPanYsqyiqFoU1om" },
      },
      updatedBy: {
        sys: { type: "Link", linkType: "User", id: "04Z9KRmPanYsqyiqFoU1om" },
      },
      publishedCounter: 12,
      version: 24,
      publishedBy: {
        sys: { type: "Link", linkType: "User", id: "04Z9KRmPanYsqyiqFoU1om" },
      },
    },
    displayField: "title",
    name: "Compliance Logo",
    description: "",
    fields: [
      {
        id: "image",
        name: "Image",
        type: "Link",
        localized: false,
        required: true,
        validations: [],
        disabled: false,
        omitted: false,
        linkType: "Asset",
      },
      {
        id: "title",
        name: "Title",
        type: "Symbol",
        localized: true,
        required: true,
        validations: [],
        disabled: false,
        omitted: false,
      },
      {
        id: "description",
        name: "Description",
        type: "Symbol",
        localized: true,
        required: true,
        validations: [],
        disabled: false,
        omitted: false,
      },
    ],
  },
  {
    sys: {
      space: { sys: { type: "Link", linkType: "Space", id: "xny2w179f4ki" } },
      id: "rooflineBanner",
      type: "ContentType",
      createdAt: "2019-02-26T18:11:08.054Z",
      updatedAt: "2019-02-26T18:11:08.458Z",
      environment: { sys: { id: "master", type: "Link", linkType: "Environment" } },
      publishedVersion: 1,
      publishedAt: "2019-02-26T18:11:08.458Z",
      firstPublishedAt: "2019-02-26T18:11:08.458Z",
      createdBy: {
        sys: { type: "Link", linkType: "User", id: "3ydnlNuap950mQsaT0TzKZ" },
      },
      updatedBy: {
        sys: { type: "Link", linkType: "User", id: "3ydnlNuap950mQsaT0TzKZ" },
      },
      publishedCounter: 1,
      version: 2,
      publishedBy: {
        sys: { type: "Link", linkType: "User", id: "3ydnlNuap950mQsaT0TzKZ" },
      },
    },
    displayField: "message",
    name: "Roofline Banner",
    description:
      "A dynamic announcement bar displayed above the top navigation used for product-specific notifications.",
    fields: [
      {
        id: "message",
        name: "Message",
        type: "Symbol",
        localized: false,
        required: true,
        validations: [],
        disabled: false,
        omitted: false,
      },
      {
        id: "ctaText",
        name: "CTA Text",
        type: "Symbol",
        localized: false,
        required: true,
        validations: [],
        disabled: false,
        omitted: false,
      },
      {
        id: "ctaUrl",
        name: "CTA URL",
        type: "Symbol",
        localized: false,
        required: true,
        validations: [
          {
            regexp: {
              pattern: "^(ftp|http|https)://(w+:{0,1}w*@)?(S+)(:[0-9]+)?(/|/([w#!:.?+=&%@!-/]))?$",
            },
          },
        ],
        disabled: false,
        omitted: false,
      },
      {
        id: "backgroundColor",
        name: "Background Color",
        type: "Symbol",
        localized: false,
        required: true,
        validations: [{ in: ["Blue", "Coral", "Teal", "Violet", "Yellow"] }],
        disabled: false,
        omitted: false,
      },
    ],
  },
  {
    sys: {
      space: { sys: { type: "Link", linkType: "Space", id: "xny2w179f4ki" } },
      id: "signupCta",
      type: "ContentType",
      createdAt: "2019-01-23T20:55:08.513Z",
      updatedAt: "2019-01-23T20:59:33.531Z",
      environment: { sys: { id: "master", type: "Link", linkType: "Environment" } },
      publishedVersion: 3,
      publishedAt: "2019-01-23T20:59:33.531Z",
      firstPublishedAt: "2019-01-23T20:55:08.873Z",
      createdBy: {
        sys: { type: "Link", linkType: "User", id: "04Z9KRmPanYsqyiqFoU1om" },
      },
      updatedBy: {
        sys: { type: "Link", linkType: "User", id: "04Z9KRmPanYsqyiqFoU1om" },
      },
      publishedCounter: 2,
      version: 4,
      publishedBy: {
        sys: { type: "Link", linkType: "User", id: "04Z9KRmPanYsqyiqFoU1om" },
      },
    },
    displayField: "placeholder",
    name: "Signup CTA",
    description: "",
    fields: [
      {
        id: "placeholder",
        name: "Placeholder",
        type: "Symbol",
        localized: true,
        required: true,
        validations: [],
        disabled: false,
        omitted: false,
      },
      {
        id: "buttonLabel",
        name: "Button label",
        type: "Symbol",
        localized: true,
        required: true,
        validations: [],
        disabled: false,
        omitted: false,
      },
    ],
  },
  {
    sys: {
      space: { sys: { type: "Link", linkType: "Space", id: "xny2w179f4ki" } },
      id: "miniTestimonials",
      type: "ContentType",
      createdAt: "2019-02-19T22:39:10.091Z",
      updatedAt: "2019-02-19T22:40:35.251Z",
      environment: { sys: { id: "master", type: "Link", linkType: "Environment" } },
      publishedVersion: 3,
      publishedAt: "2019-02-19T22:40:35.251Z",
      firstPublishedAt: "2019-02-19T22:39:10.381Z",
      createdBy: {
        sys: { type: "Link", linkType: "User", id: "3ydnlNuap950mQsaT0TzKZ" },
      },
      updatedBy: {
        sys: { type: "Link", linkType: "User", id: "3ydnlNuap950mQsaT0TzKZ" },
      },
      publishedCounter: 2,
      version: 4,
      publishedBy: {
        sys: { type: "Link", linkType: "User", id: "3ydnlNuap950mQsaT0TzKZ" },
      },
    },
    displayField: null,
    name: "Mini Testimonials",
    description:
      "Collection of Mini Testimonial Cards - quotes and sources shown for site visitors to read snippets about Intercom successes.",
    fields: [
      {
        id: "testimonials",
        name: "Testimonials",
        type: "Array",
        localized: false,
        required: true,
        validations: [{ size: { min: 2 } }],
        disabled: false,
        omitted: false,
        items: {
          type: "Link",
          validations: [{ linkContentType: ["testimonialMiniCard"] }],
          linkType: "Entry",
        },
      },
    ],
  },
]

generateTypes(contentTypes as any).then(source => console.log(source))
